vich_uploader:
    db_driver: orm

    mappings:
        my_profile_images:
           uri_prefix: '/images/my_profile'
           upload_destination: '%kernel.project_dir%/public/images/my_profile'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
